### ISSUE TITLE
Unable to run the main branch

### ISSUE THREAD

**Issue by tariq235** [Dimillian/RunewordsApp#2]
<img width="1512" alt="Screenshot 2022-11-30 at 1 46 29 PM" src="https://user-images.githubusercontent.com/349211/204743225-d81aec1f-de62-464e-85e9-156ba166b81d.png">

Any help would be highly appreciated. I am running on Xcode Version 14.1

**Comment by Dimillian** [comment]
You're on the wrong repo, but it's fine, I've just pushed for fixing the build, thanks!
